name: PR Reviewer with OpenAI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      - name: Get changed files
        id: files
        run: |
          base_commit=${{ github.event.pull_request.base.sha }}
          head_commit=${{ github.sha }}

          echo "Base commit: $base_commit"
          echo "Head commit: $head_commit"

          changed_files=$(git diff --name-only $base_commit $head_commit)

          if [ -z "$changed_files" ]; then
            echo "No files changed."
            echo "review_result=No changes detected." >> $GITHUB_ENV
          else
            # Convert changed files to array and pass to OpenAI action
            changed_files_array=($changed_files)

            # Use OpenAI action for review
            echo "Running OpenAI review..."
            response=$(curl -s -X POST https://api.openai.com/v1/completions \
              -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
              -H "Content-Type: application/json" \
              -d '{
                "model": "text-davinci-003",
                "prompt": "Review the following files:\n'${changed_files_array[@]}'",
                "max_tokens": 150
              }')

            echo "review_result=$(echo $response | jq -r '.choices[0].text')" >> $GITHUB_ENV
          fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Automated PR Review by OpenAI
            ${{ env.review_result }}
